### ISSUE TITLE
redisco.models.attributes.ReferenceField.__get__ does not read from instance

### ISSUE THREAD

**Issue by clayg** [iamteem/redisco#2]
given app/models.py as:

<pre>
from redisco import models

class Department(models.Model):
    name = models.Attribute(required=True)

class Person(models.Model):
    name = models.Attribute(required=True)
    #manager = models.ReferenceField('Person', related_name='underlings')
    department = models.ReferenceField(Department)
</pre>

You can see that ReferenceField is correctly handling the _manager_id in __set__, but the **get** is caching the referenced model on the ReferenceField instance instead of the Model instance:

<pre>
&gt;&gt;&gt; from app import models
&gt;&gt;&gt; d1 = models.Department(name='Accounting')
&gt;&gt;&gt; d1.save()
True
&gt;&gt;&gt; d2 = models.Department(name='Billing')
&gt;&gt;&gt; d2.save()
True
&gt;&gt;&gt; p1 = models.Person(name='Joe', department=d1)
&gt;&gt;&gt; p1.save()
True
&gt;&gt;&gt; p1
&lt;Person:1 {'department': &lt;Department:1 {'name': 'Accounting'}&gt;, 'name': 'Joe', 'department_id': '1'}&gt;
&gt;&gt;&gt; p2 = models.Person(name='Jack', department=d2)
&gt;&gt;&gt; p2.save()
True
&gt;&gt;&gt; p2
&lt;Person:2 {'department': &lt;Department:1 {'name': 'Accounting'}&gt;, 'name': 'Jack', 'department_id': '2'}&gt;</pre>

N.B.
<pre>
>>> p2.department_id
'2'
>>> p2.department.id
'1'
</pre>

**Comment by clayg** [comment]
I don't think it was intentional for this test to pass:

<pre>
        Character.objects.create(n=32, m='a', word=word)
        Character.objects.create(n=33, m='b', word=word)
        Character.objects.create(n=34, m='c', word=word)
        Character.objects.create(n=34, m='d')
        for char in Character.objects.all():
            self.assertEqual(word, char.word)
</pre>


Later we assert:
        self.assertTrue(d not in word.character_set)

So I'm going to change this test.

**Comment by clayg** [comment]
fixed in fork:
http://github.com/clayg/redisco

submitted pull request.

**Comment by iamteem** [comment]
Thanks! :D
